name: c_editor
description: "Level Editor for Plants vs. Zombies 2 Chinese"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  collection: ^1.18.0
  convert: ^3.1.2
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  file_picker: ^10.3.10
  path: ^1.8.3
  permission_handler: ^11.3.1
  archive: ^4.0.2
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1
  rijndael: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/reference/template/
    - assets/meta/icon.png
    - assets/meta/links.json
    - assets/meta/properties.json
    - assets/reference/
    - assets/resources/
    - assets/l10n/resource_en.json
    - assets/l10n/resource_zh.json
    - assets/l10n/resource_ru.json
    - assets/images/
    - assets/images/plants/
    - assets/images/zombies/
    - assets/images/round_icons/
    - assets/images/tags/
    - assets/images/griditems/
    - assets/images/tools/
    - assets/images/others/
    - assets/images/fish/
    - assets/images/tunnels/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/meta/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/meta/icon.png"
    background_color: "#ffffff"
    theme_color: "#1976d2"
  windows:
    generate: true
    image_path: "assets/meta/icon.png"
  macos:
    generate: true
    image_path: "assets/meta/icon.png"
  linux:
    generate: true
    image_path: "assets/meta/icon.png"
